/* Routing for the private beta: cached, user-triggered requests, no live traffic. */
let routeQueue133=Promise.resolve(),routeLast133=0;
function routeKey133(value){let hash=2166136261;for(const ch of String(value||'').trim().toLowerCase())hash=Math.imul(hash^ch.charCodeAt(0),16777619);return (hash>>>0).toString(36)}
function routeCache133(key,value){try{if(value){localStorage.setItem(key,JSON.stringify({at:Date.now(),value}));return value}const c=JSON.parse(localStorage.getItem(key)||'null');return c&&Date.now()-c.at<30*86400000?c.value:null}catch(_){return null}}
function routeFetch133(url){const job=routeQueue133.catch(()=>{}).then(async()=>{await new Promise(r=>setTimeout(r,Math.max(0,1100-(Date.now()-routeLast133))));routeLast133=Date.now();const controller=new AbortController(),timer=setTimeout(()=>controller.abort(),15000);try{const response=await fetch(url,{signal:controller.signal,headers:{Accept:'application/json'}});if(response.status===429)throw Error('El servicio de mapas está ocupado. Espera un minuto antes de reintentar.');if(!response.ok)throw Error('El servicio de mapas no está disponible en este momento.');return await response.json()}catch(e){if(e.name==='AbortError')throw Error('El servicio de mapas ha tardado demasiado. Vuelve a intentarlo.');if(e instanceof TypeError)throw Error('No se pudo conectar con el servicio de mapas. Comprueba la conexión y vuelve a intentarlo.');throw e}finally{clearTimeout(timer)}});routeQueue133=job;return job}
geocodeLocation=async function(location){const query=String(location||'').trim();if(!query)return null;const key='ritmo-photon-v1:'+routeKey133(query),cached=routeCache133(key);if(cached)return cached;const data=await routeFetch133('https://photon.komoot.io/api/?limit=1&q='+encodeURIComponent(query)),feature=data.features?.[0],coords=feature?.geometry?.coordinates;if(!coords||!Number.isFinite(coords[0])||!Number.isFinite(coords[1]))return null;const p=feature.properties||{},point={lon:coords[0],lat:coords[1],label:[p.name,p.city,p.state,p.country].filter((x,i,a)=>x&&a.indexOf(x)===i).join(', ')};routeCache133(key,point);return point};
function routeMatches133(route,location,km){return route&&route.origin===routeKey133(window.userSettings?.home_address)&&route.destination===String(location||'').trim()&&Math.abs(Number(route.km)-Number(km))<0.05&&Number(route.minutes)>0}
function routeForSave133(existing,location,km){const fresh=document.getElementById('broute')?._estimate133,previous=existing?.readiness_options?.route_estimate;return routeMatches133(fresh,location,km)?fresh:routeMatches133(previous,location,km)?previous:null}
calculateRouteFromForm=async function(){const field=document.getElementById('blocation'),destination=field?.value.trim(),origin=window.userSettings?.home_address?.trim(),out=document.getElementById('routeResult'),button=document.getElementById('broute'),kmField=document.getElementById('bkm');if(!origin||!destination){out.textContent='Configura el domicilio en Ajustes y la ubicación del bolo.';return}if(button.disabled)return;button.disabled=true;out.textContent='Buscando direcciones y calculando ruta…';try{const a=await geocodeLocation(origin);if(!a)throw Error('No se encontró el domicilio. Añade calle, localidad y provincia en Ajustes.');const b=await geocodeLocation(destination);if(!b)throw Error('No se encontró el destino. Añade localidad y provincia.');const key='ritmo-route-v1:'+routeKey133(JSON.stringify([a.lat,a.lon,b.lat,b.lon]));let route=routeCache133(key);if(!route){const data=await routeFetch133(`https://router.project-osrm.org/route/v1/driving/${a.lon},${a.lat};${b.lon},${b.lat}?overview=false`);route=data.routes?.[0];if(data.code!=='Ok'||!route||!Number.isFinite(route.distance)||!Number.isFinite(route.duration))throw Error('No se encontró una ruta por carretera entre esas ubicaciones.');route={distance:route.distance,duration:route.duration};routeCache133(key,route)}if(!field.isConnected||field.value.trim()!==destination||window.userSettings?.home_address?.trim()!==origin)return;const km=Math.round(route.distance/1000*2*10)/10,minutes=Math.max(1,Math.round(route.duration/60));kmField.value=km;button._estimate133={origin:routeKey133(origin),destination,km,minutes,provider:'OSRM',calculated_at:new Date().toISOString()};out.textContent=`${km.toLocaleString('es-ES')} km ida y vuelta · ${minutes} min de ida (sin tráfico en directo). Destino: ${b.label||destination}.`;out.insertAdjacentHTML('beforeend',' <a href="https://www.openstreetmap.org/copyright" target="_blank" rel="noopener">© OpenStreetMap</a> · Photon / OSRM.');}catch(e){if(out.isConnected)out.textContent=e.message+' Puedes introducir los kilómetros manualmente.'}finally{if(button.isConnected)button.disabled=false}};
const routeTravelBase133=travelInfo;
travelInfo=function(g){const t=routeTravelBase133(g),estimate=g?.readiness_options?.route_estimate;if(routeMatches133(estimate,g.location,g.kilometers)){t.minutes=Number(estimate.minutes);t.withMargin=t.minutes+t.margin;t.source='route'}else t.source='speed';return t};
// Same-context links avoid opening an empty child window in installed iOS apps.
function openMaps133(url){window.location.assign(url)}
openBoloRouteFromForm=function(){const destination=document.getElementById('blocation')?.value.trim();if(!destination)return;const origin=window.userSettings?.home_address?.trim();openMaps133('https://www.google.com/maps/dir/?api=1&travelmode=driving&destination='+encodeURIComponent(destination)+(origin?'&origin='+encodeURIComponent(origin):''))};
document.addEventListener('click',event=>{const a=event.target.closest?.('a[href]');if(!a)return;try{const url=new URL(a.href);if(url.hostname==='www.google.com'&&url.pathname.startsWith('/maps/'))a.target='_self'}catch(_){}});
