/* RITMO 1.33. Solo se muestran campos devueltos por el RPC social. */
let social133={friends:[],events:[],feed:[],posts:[],cheers:[],memories:[],code:''};
let socialWriting133=false;
let socialOwner133=null,socialLoading133=false,socialError133='',socialTab133='today',socialEventId133=null,socialPending133=null;
const socialPhotos133=new Map();
function socialIcon133(){return '<span class="social-inline-icon" aria-hidden="true"><svg viewBox="0 0 24 24"><circle cx="9" cy="8" r="3"/><path d="M3 21v-3a6 6 0 0 1 12 0v3M16 5a3 3 0 0 1 0 6M18 15a5 5 0 0 1 3 4v2"/></svg></span>'}
function socialReset133(){social133={friends:[],events:[],feed:[],posts:[],cheers:[],memories:[],code:''};socialOwner133=session?.user?.id||null;socialPhotos133.clear();socialError133='';socialPending133=null;socialLoading133=false;socialEventId133=null}
async function socialRpc133(action,data={}){const {data:result,error}=await db.rpc('ritmo_social',{p_action:action,p_data:data});if(error)throw Error(error.message||'No se pudo completar la acción');return result}
async function loadSocial133(redraw=true){const owner=session?.user?.id;if(!owner||accountBlocked132)return;if(socialOwner133!==owner)socialReset133();if(socialPending133)return socialPending133;socialLoading133=true;socialError133='';const task=(async()=>{try{const data=await socialRpc133('state');if(session?.user?.id!==owner||socialOwner133!==owner)return;if(!data||!Array.isArray(data.events))throw Error('No se ha podido leer Amigos');social133=data;for(const key of ['friends','feed','posts','cheers','memories'])social133[key]??=[];await Promise.allSettled(social133.memories.filter(m=>m.photo_path).map(async m=>{const cached=socialPhotos133.get(m.photo_path);if(cached&&cached.expires>Date.now())return;const {data,error}=await db.storage.from('ritmo-social').createSignedUrl(m.photo_path,300);if(!error&&session?.user?.id===owner)socialPhotos133.set(m.photo_path,{url:data.signedUrl,expires:Date.now()+240000})}));}catch(e){if(session?.user?.id===owner)socialError133=e.message}finally{if(session?.user?.id===owner){socialLoading133=false;if(redraw&&!document.getElementById('modal'))render()}}})();socialPending133=task;try{await task}finally{if(socialPending133===task)socialPending133=null}}
const socialMenuBase133=menuItems132;
menuItems132=function(){const items=socialMenuBase133();items.splice(items.findIndex(x=>x[0]==='projects'),0,['friends','Amigos']);return items};
const socialMenuIconBase133=originalMenuIcon1321;
originalMenuIcon1321=function(id){return id==='friends'?'<span class="dn-icon">'+socialIcon133()+'</span>':socialMenuIconBase133(id)};
const socialRenderBase133=render;
render=function(){if(session&&!needsAccountSetup()&&!accountBlocked132&&['friends','shared'].includes(view)){root.innerHTML=shell(view==='friends'?friendsPage133():sharedPage133(socialEventId133));return}socialRenderBase133()};
const socialGoBase133=go;
go=function(v){socialGoBase133(v);if(v==='friends')loadSocial133()};
const socialStartBase133=startAccount;
startAccount=async function(){await socialStartBase133();if(session&&!needsAccountSetup()&&!accountBlocked132){await loadSocial133();const code=new URLSearchParams(location.search).get('friend');if(code&&/^[A-Za-z0-9]{12}$/.test(code)){socialTab133='friends';go('friends');modalAddFriend133(code)}}};
const socialActivityBase133=activityFeed;
activityFeed=function(){const out=socialActivityBase133();if(socialOwner133!==session?.user?.id)return out;const requests=social133.friends.filter(f=>f.state==='pending'&&f.incoming).length,invites=social133.events.filter(e=>e.membership==='invited').length,changes=social133.events.filter(e=>e.membership==='accepted'&&e.owner_id!==session.user.id&&e.seen_revision<e.revision).length,notes=social133.cheers.filter(c=>c.incoming&&!c.seen).length;if(requests)out.push(['♧',`${requests} solicitud${requests===1?'':'es'} de amistad`,'Abre Amigos para responder.','friends']);if(invites)out.push(['♫',`${invites} invitación${invites===1?'':'es'} a un bolo`,'Elige tu proyecto o vincula un bolo existente.','friends']);if(changes)out.push(['↻',`${changes} bolo${changes===1?'':'s'} compartido${changes===1?'':'s'} actualizado${changes===1?'':'s'}`,'Revisa los datos y marca el aviso como visto.','friends']);if(notes)out.push(['♡',`${notes} mensaje${notes===1?'':'s'} de ánimo`,'Tus amigos te han escrito.','friends']);return out};
function socialEventForBolo133(id){return social133.events.find(e=>e.personal_bolo===id&&e.membership==='accepted')}
function socialPasses133(e,id){return (e.passes||[]).map((p,i)=>({...p,id:'shared-'+i,bolo_id:id,pass_type_id:null}))}
const socialReadinessBase133=boloReadiness;
boloReadiness=function(g){const r=socialReadinessBase133(g),e=socialEventForBolo133(g.id);if(e&&e.owner_id!==session?.user?.id){r.steps=r.steps.map(([name,ok])=>[name,name==='Pases'?(e.passes||[]).length>0:name==='Programa'?ok||Boolean(e.program_url):ok]);r.missing=r.steps.filter(x=>!x[1]).map(x=>x[0]);r.done=r.total-r.missing.length}return r};
const socialRouteModelBase133=routeSheetModel131;
routeSheetModel131=function(g,selected){const e=socialEventForBolo133(g.id),model=socialRouteModelBase133(g,selected);if(e&&e.owner_id!==session?.user?.id&&selected.includes('program')&&socialSafeUrl133(e.program_url)){const block=model.blocks.find(b=>b.title==='Programa');if(block){block.lines=['Programa compartido por el organizador'];block.link=socialSafeUrl133(e.program_url)}}return model};
const socialExtrasBase133=loadBoloExtras;
loadBoloExtras=async function(id){await Promise.all([socialExtrasBase133(id),loadSocial133(false)]);const shared=socialEventForBolo133(id);if(shared&&shared.owner_id!==session.user.id){boloPasses=socialPasses133(shared,id);allBoloPasses=allBoloPasses.filter(p=>p.bolo_id!==id).concat(boloPasses.map(p=>({bolo_id:id})));if(nextGig()?.id===id)homeNextPasses=boloPasses.slice()}};
const socialHomePassBase133=loadHomeNextPasses;
loadHomeNextPasses=async function(){await socialHomePassBase133();await loadSocial133(false);const id=nextGig()?.id,e=socialEventForBolo133(id);if(e&&e.owner_id!==session?.user?.id)homeNextPasses=socialPasses133(e,id)};
const socialDetailBase133=detail;
detail=function(id){let html=socialDetailBase133(id),e=socialEventForBolo133(id);const widget=`<section class="social-card social-widget"><div class="social-top"><h2>${socialIcon133()} Lo hacemos juntos</h2></div>${e?`<p>${esc(e.title)} · ${(e.members||[]).filter(m=>m.state==='accepted').length} participantes</p>${e.seen_revision<e.revision&&e.owner_id!==session.user.id?'<div class="social-update">Hay cambios compartidos pendientes de revisar.</div>':''}<button class="secondary" onclick="openShared133('${e.id}')">Ver compañeros y datos compartidos</button>`:'<p class="muted">Invita a amigos de RITMO para compartir fecha, destino y horarios.</p><button class="secondary" onclick="modalShareBolo133(\''+id+'\')">Invitar compañeros</button>'}<div class="social-actions"><button class="secondary" onclick="modalPublish133('${id}')">${social133.posts.find(p=>p.bolo_id===id)?.visible?'Editar publicación para amigos':'Compartir en «Hoy tocan…»'}</button></div></section>`;html=html.replace('<section class="detail">',widget+'<section class="detail">');if(e&&e.owner_id!==session.user.id){html=html.replace(/<button[^>]*onclick="(?:modalPass|deletePass)\([^"]*"[^>]*>[\s\S]*?<\/button>/g,'');html=html.replace('<h3>Pases</h3>','<h3>Pases</h3><p class="muted">Horarios compartidos por '+esc(e.owner_name)+'. Se actualizan con el organizador.</p>')}return html};
const socialModalBoloBase133=modalBolo;
modalBolo=function(id=''){socialModalBoloBase133(id);const e=socialEventForBolo133(id);if(e&&e.owner_id!==session?.user?.id){for(const field of ['bdate','bstatus','blocation']){const input=document.getElementById(field);if(input)input.disabled=true}document.querySelector('#modal form')?.insertAdjacentHTML('afterbegin','<p class="muted">Fecha, estado y destino los mantiene el organizador. Tu precio, kilómetros, gastos y notas son privados. Puedes desvincularte desde el espacio compartido.</p>')}};
function socialTabs133(tab){socialTab133=tab;render()}
function socialInitial133(name){return esc((name||'R').trim().slice(0,1).toUpperCase())}
function friendsPage133(){return `${pageTitle('Amigos')}<div class="social-toolbar"><p class="muted">Compartir escenario, acompañarse.</p><button class="secondary" onclick="loadSocial133()">Actualizar</button></div>${socialError133?`<div class="error" role="alert">No se pudo actualizar Amigos: ${esc(socialError133)}</div>`:''}${socialLoading133?'<p role="status" class="muted">Actualizando Amigos…</p>':''}${socialInvitations133()}<nav class="social-tabs" aria-label="Apartados de Amigos">${[['today','Hoy tocan…'],['friends','Mis amigos'],['events','Juntos'],['messages','Ánimos']].map(([id,title])=>`<button class="${socialTab133===id?'active':''}" aria-pressed="${socialTab133===id}" onclick="socialTabs133('${id}')">${title}</button>`).join('')}</nav>${socialTab133==='friends'?socialFriends133():socialTab133==='events'?socialEvents133():socialTab133==='messages'?socialCheers133():socialFeed133()}`}
function socialInvitations133(){const requests=social133.friends.filter(f=>f.state==='pending'&&f.incoming),events=social133.events.filter(e=>e.membership==='invited');return requests.map(f=>`<section class="social-card"><b>${esc(f.name)} quiere ser tu amigo</b><div class="social-actions"><button class="primary" onclick="socialAction133(this,'friend',{id:'${f.id}',state:'accepted'})">Aceptar amistad</button><button class="secondary" onclick="socialAction133(this,'friend',{id:'${f.id}',state:'declined'})">Rechazar</button><button class="secondary" onclick="socialAction133(this,'friend',{id:'${f.id}',state:'blocked'})">Bloquear</button></div></section>`).join('')+events.map(e=>`<section class="social-card"><span class="social-pill">Invitación a un bolo</span><h3>${esc(e.title)}</h3><p>${esc(e.owner_name)} · ${esc(e.event_date)}</p><div class="social-actions"><button class="primary" onclick="modalAcceptShared133('${e.id}')">Lo hacemos juntos</button><button class="secondary" onclick="socialAction133(this,'decline',{event:'${e.id}'})">Rechazar</button></div></section>`).join('')}
function socialFriends133(){return `<section class="social-card"><h2>Tu código de amigo</h2><p class="muted">Compártelo con quien quieras agregar. La otra persona te enviará una solicitud.</p><div class="social-code">${esc(social133.code||'Cargando…')}</div><div class="social-actions"><button class="secondary" onclick="shareFriendCode133(this)">Compartir mi enlace</button><button class="primary" onclick="modalAddFriend133()">Añadir amigo</button></div></section><section class="social-card"><h2>Mis amigos</h2>${social133.friends.filter(f=>f.state==='accepted').map(f=>`<div class="social-person"><span class="social-monogram">${socialInitial133(f.name)}</span><div class="grow"><b>${esc(f.name)}</b><small>${Number(f.together)||0} actuaciones juntos</small><div class="social-actions"><button class="secondary" onclick="modalFriendManage133('${f.id}')">Gestionar</button></div></div></div>`).join('')||'<p class="muted">Todavía no tienes amigos conectados.</p>'}</section>${social133.friends.filter(f=>f.state==='pending'&&!f.incoming).map(f=>`<section class="social-card"><b>${esc(f.name)}</b><small>Solicitud enviada · pendiente de aceptar</small><button class="secondary" onclick="socialAction133(this,'friend',{id:'${f.id}',state:'removed'})">Retirar solicitud</button></section>`).join('')}${social133.friends.filter(f=>f.state==='blocked'&&f.blocked_by_me).map(f=>`<section class="social-card"><b>${esc(f.name)}</b><small>Bloqueado</small><button class="secondary" onclick="socialAction133(this,'friend',{id:'${f.id}',state:'removed'})">Desbloquear</button></section>`).join('')}`}
function socialFeed133(){return `<p class="social-subtle">Solo aparecen los bolos que tus amigos deciden compartir para hoy. Las localidades las eligen ellos.</p>${social133.feed.map(p=>`<article class="social-card"><div class="social-person"><span class="social-monogram">${socialInitial133(p.name)}</span><div><b>${esc(p.name)} toca hoy</b><small>${esc(p.city)}</small></div></div><div class="social-feed-project">${esc(p.project)}</div><div class="social-actions"><button class="secondary" onclick="socialAction133(this,'cheer',{post:'${p.id}',message:'¡Buen bolo!'})">¡Buen bolo!</button><button class="secondary" onclick="socialAction133(this,'cheer',{post:'${p.id}',message:'¡A disfrutar!'})">¡A disfrutar!</button><button class="primary" onclick="modalCheer133('${p.id}')">Enviar ánimo</button></div></article>`).join('')||`<section class="social-card social-empty">${socialIcon133()}<h3>Hoy aún no hay actuaciones compartidas</h3><p>Tus amigos aparecerán aquí cuando publiquen un bolo. Puedes compartir el tuyo desde su ficha.</p><button class="secondary" onclick="socialTabs133('friends')">Conectar con amigos</button></section>`}`}
function socialEvents133(){return social133.events.filter(e=>e.membership==='accepted').sort((a,b)=>a.event_date.localeCompare(b.event_date)).map(e=>`<section class="social-card"><span class="social-pill">${e.state==='cancelled'?'Cancelado':e.event_date<localDate()?'Recuerdo compartido':'Lo hacemos juntos'}</span><h3>${esc(e.title)}</h3><p>${esc(e.event_date)} · ${esc(e.location||'Destino pendiente')}</p><small>Organiza ${esc(e.owner_name)}</small>${e.seen_revision<e.revision&&e.owner_id!==session.user.id?'<p class="social-update">Cambios pendientes de revisar</p>':''}<div class="social-actions"><button class="primary" onclick="openShared133('${e.id}')">Ver bolo compartido</button>${e.personal_bolo?`<button class="secondary" onclick="goGig('${e.personal_bolo}')">Mi ficha personal</button>`:''}</div></section>`).join('')||'<section class="social-card"><h3>Vuestros bolos, juntos</h3><p class="muted">Abre la ficha de un bolo y pulsa «Invitar compañeros».</p></section>'}
function socialCheers133(){return `<section class="social-card"><div class="social-top"><h2>Mensajes de ánimo</h2><button class="secondary" onclick="socialAction133(this,'read_cheers',{})">Marcar leídos</button></div><p class="social-subtle">Las notas son privadas entre quien las envía y quien las recibe.</p>${social133.cheers.map(c=>`<article class="social-person"><span class="social-monogram">${socialInitial133(c.name)}</span><div class="grow"><b>${c.incoming?'De':'Para'} ${esc(c.name)}</b>${c.incoming&&!c.seen?' <span class="social-pill">Nuevo</span>':''}<p class="social-note">${esc(c.message)}</p><small>${socialDate133(c.created_at)}</small></div></article>`).join('')||'<p class="muted">Tus mensajes aparecerán aquí.</p>'}</section>`}
function socialDate133(value){return new Date(value).toLocaleString('es-ES',{dateStyle:'short',timeStyle:'short'})}
function socialModal133(title,body){closeModal();document.body.insertAdjacentHTML('beforeend',`<div class="modal-bg" id="modal"><div class="modal"><div class="modal-head"><h2>${title}</h2><button type="button" aria-label="Cerrar" onclick="closeModal()">✕</button></div>${body}<div id="socialModalError133" role="status"></div></div></div>`)}
async function socialAction133(button,action,data){if(button?.disabled||socialWriting133)return;socialWriting133=true;const owner=session?.user?.id;if(button)button.disabled=true;try{if(socialPending133)await socialPending133;const result=await socialRpc133(action,data);if(session?.user?.id!==owner)return;await loadSocial133(false);if(['accept','leave','remove'].includes(action))await loadGigs();closeModal();render();if(action==='cheer')socialToast133('Ánimo enviado');return result}catch(e){const target=document.getElementById('socialModalError133');if(target)target.innerHTML=`<div class="error">${esc(e.message)}</div>`;else alert(e.message)}finally{socialWriting133=false;if(button)button.disabled=false}}
function socialToast133(text){const el=document.createElement('div');el.className='social-update';el.setAttribute('role','status');el.textContent=text;root.querySelector('main')?.prepend(el);setTimeout(()=>el.remove(),3500)}
function modalAddFriend133(code=''){socialModal133('Añadir amigo',`<form class="form" onsubmit="requestFriend133(event)"><p class="muted">Pídele su código de Amigos. Le llegará una solicitud dentro de RITMO.</p><label>Código de amigo<input id="friendCode133" required maxlength="200" value="${esc(code)}" autocomplete="off" autocapitalize="characters" placeholder="Código o enlace de RITMO"></label><button class="primary">Enviar solicitud</button></form>`)}
async function requestFriend133(event){event.preventDefault();let code=document.getElementById('friendCode133').value.trim();try{if(code.startsWith('https://'))code=new URL(code).searchParams.get('friend')||''}catch(_e){}await socialAction133(event.target.querySelector('button'),'request',{code});}
async function shareFriendCode133(button){if(!social133.code)return;const url=new URL(location.href);url.search='';url.hash='';url.searchParams.set('friend',social133.code);try{if(navigator.share)await navigator.share({title:'Conectemos en RITMO',text:'Añádeme como amigo en RITMO',url:url.href});else{await navigator.clipboard.writeText(url.href);button.textContent='Enlace copiado'}}catch(e){if(e.name!=='AbortError')socialModal133('Tu enlace de amigo',`<p>Selecciona y copia este enlace:</p><input readonly value="${esc(url.href)}">`)}}
function modalFriendManage133(id){const f=social133.friends.find(f=>f.id===id);if(!f)return;socialModal133('Gestionar amistad',`<h3>${esc(f.name)}</h3><p>Quitar la amistad oculta las publicaciones y los ánimos. Los bolos compartidos se mantienen hasta que te desvincules.</p><p>Bloquear impide nuevas solicitudes y retira la participación entre los bolos que organizáis el uno para el otro. Las fichas personales se conservan.</p><div class="social-actions"><button class="secondary" onclick="socialAction133(this,'friend',{id:'${id}',state:'removed'})">Quitar amistad</button><button class="secondary danger" onclick="socialAction133(this,'friend',{id:'${id}',state:'blocked'})">Bloquear</button></div>`)}
function modalShareBolo133(id){const g=gigs.find(g=>g.id===id);if(!g)return;socialModal133('Compartir este bolo',`<h3>${esc(projectById(g.project_id).name)}</h3><p>${esc(g.event_date)} · ${esc(g.location||'Destino pendiente')}</p><p>Los compañeros que acepten verán el proyecto, fecha, destino exacto, horarios y participantes. Cada uno conserva privados su precio, cobros, gastos, domicilio, kilómetros, checklist y notas.</p><form class="form" onsubmit="createShared133(event,'${id}')"><label class="export-check"><input type="checkbox" id="shareProgram133"> Compartir también el programa adjunto y sus futuras actualizaciones</label><button class="primary">Crear espacio y elegir compañeros</button></form>`)}
async function createShared133(event,id){event.preventDefault();const button=event.target.querySelector('button');button.disabled=true;try{const result=await socialRpc133('share',{bolo:id,program:document.getElementById('shareProgram133').checked});await loadSocial133(false);closeModal();socialEventId133=result.id;view='shared';render();modalInviteShared133(result.id)}catch(e){document.getElementById('socialModalError133').innerHTML=`<div class="error">${esc(e.message)}</div>`}finally{button.disabled=false}}
function modalInviteShared133(id){const e=social133.events.find(e=>e.id===id),friends=social133.friends.filter(f=>f.state==='accepted'&&!(e?.members||[]).some(m=>m.user_id===f.user_id));socialModal133('Invitar compañeros',`<p>Cada amigo tendrá que aceptar antes de que el bolo aparezca en su agenda.</p>${friends.map(f=>`<div class="social-person"><span class="grow">${esc(f.name)}</span><button class="secondary" onclick="socialAction133(this,'invite',{event:'${id}',user:'${f.user_id}'})">Invitar</button></div>`).join('')||'<p class="muted">No hay amigos disponibles para invitar. Agrega amigos desde el menú Amigos.</p>'}`)}
function modalAcceptShared133(id){const e=social133.events.find(e=>e.id===id);if(!e)return;const available=gigs.filter(g=>!socialEventForBolo133(g.id));socialModal133('Lo hacemos juntos',`<h3>${esc(e.title)}</h3><p>${esc(e.event_date)} · Organiza ${esc(e.owner_name)}</p><p>La fecha, el estado, el destino y los horarios los mantiene el organizador. Tu información personal seguirá siendo privada.</p><form class="form" onsubmit="acceptShared133(event,'${id}')"><label>¿Ya tienes este bolo?<select id="socialExisting133"><option value="">Crear en mi agenda</option>${available.map(g=>`<option value="${g.id}">${esc(g.event_date)} · ${esc(projectById(g.project_id).name)} · ${esc(g.location||'')}</option>`).join('')}</select></label><label>Proyecto para un bolo nuevo<select id="socialProject133"><option value="">Selecciona tu proyecto</option>${projects.filter(p=>p.active).map(p=>`<option value="${p.id}">${esc(p.name)}</option>`).join('')}</select></label><p class="muted">Si creas uno nuevo se usará tu caché habitual de ese proyecto. Los kilómetros quedarán pendientes de calcular desde tu domicilio. Si vinculas uno existente conservarás sus datos privados.</p>${!projects.some(p=>p.active)?'<button type="button" class="secondary" onclick="closeModal();go(\'projects\')">Crear mi primer proyecto</button>':''}<button class="primary">Aceptar y añadir a mi agenda</button></form>`)}
async function acceptShared133(event,id){event.preventDefault();const button=event.target.querySelector('button.primary');const result=await socialAction133(button,'accept',{event:id,bolo:document.getElementById('socialExisting133').value,project:document.getElementById('socialProject133').value});if(result?.bolo){await loadHomeNextPasses();await goGig(result.bolo)}}
async function openShared133(id){socialEventId133=id;view='shared';render();await loadSocial133()}
function sharedPage133(id){const e=social133.events.find(e=>e.id===id&&e.membership==='accepted');if(!e)return `${pageTitle('Bolo compartido',"go('friends')")}<section class="social-card"><p>${socialLoading133?'Cargando bolo…':'Este espacio ya no está disponible para tu cuenta.'}</p><button class="secondary" onclick="go('friends')">Volver a Amigos</button></section>`;const owner=e.owner_id===session.user.id;return `${pageTitle('Lo hacemos juntos',"go('friends')")}<section class="social-card"><span class="social-pill">${e.state==='cancelled'?'Cancelado':'Bolo compartido'}</span><h2>${esc(e.title)}</h2><p>${esc(e.event_date)} · ${esc(e.location||'Destino pendiente')}</p><small>Organiza ${esc(e.owner_name)}</small>${e.seen_revision<e.revision&&!owner?`<div class="social-update">Se han actualizado los datos compartidos. Revisa fecha, destino, horarios y programa.<button class="secondary" onclick="socialAction133(this,'seen',{event:'${e.id}'})">Visto, estoy al día</button></div>`:''}<h3>Horarios compartidos</h3>${(e.passes||[]).map(p=>`<div class="line"><span>Pase ${Number(p.pass_number)} · ${esc(p.standard_type)}</span><b>${esc((p.start_time||'').slice(0,5))}${p.end_time?' – '+esc(p.end_time.slice(0,5)):''}</b></div>`).join('')||'<p class="muted">El organizador aún no ha añadido horarios.</p>'}<div class="social-actions">${e.location?`<a class="secondary" href="https://www.google.com/maps/search/?api=1&query=${encodeURIComponent(e.location)}" target="_self" rel="noopener">Ver ubicación</a>`:''}${socialSafeUrl133(e.program_url)?`<a class="secondary" href="${esc(socialSafeUrl133(e.program_url))}" target="_blank" rel="noopener">Ver programa compartido</a>`:''}${e.personal_bolo?`<button class="secondary" onclick="goGig('${e.personal_bolo}')">Mi ficha y hoja de ruta</button>`:''}</div><p class="social-subtle">Tu hora de salida y tus datos económicos se consultan en tu ficha personal.</p></section><section class="social-card"><h2>Compañeros</h2>${(e.members||[]).map(m=>`<div class="social-person"><span class="social-monogram">${socialInitial133(m.name)}</span><div class="grow"><b>${esc(m.name)}</b><small>${m.user_id===e.owner_id?'Organizador':m.state==='invited'?'Invitación pendiente':m.seen?'Al día · visto':'Pendiente de revisar cambios'}</small></div>${owner&&m.user_id!==session.user.id?`<button class="secondary" onclick="modalLeaveShared133('${e.id}','${m.user_id}')">Retirar</button>`:''}</div>`).join('')}<div class="social-actions">${owner?`<button class="primary" onclick="modalInviteShared133('${e.id}')">Invitar compañeros</button>${e.personal_bolo?`<button class="secondary" onclick="modalProgramShared133('${e.id}')">Programa compartido</button>`:''}`:`<button class="secondary" onclick="modalLeaveShared133('${e.id}')">Desvincularme</button>`}</div></section>${socialMemories133(e)}`}
function socialSafeUrl133(value){try{const u=new URL(value);return ['https:','http:'].includes(u.protocol)?u.href:''}catch(_e){return ''}}
function modalProgramShared133(id){const e=social133.events.find(e=>e.id===id);socialModal133('Programa compartido',`<p>Los participantes ${e.share_program?'dejarán de ver':'podrán consultar'} el enlace al programa de este bolo y sus futuras actualizaciones.</p><button class="primary" onclick="socialAction133(this,'share',{bolo:'${e.personal_bolo}',program:${!e.share_program}})">${e.share_program?'Dejar de compartir programa':'Compartir programa'}</button>`)}
function modalLeaveShared133(id,user=''){socialModal133(user?'Retirar compañero':'Desvincularme',`<p>La ficha personal y sus cobros se conservarán. Dejará de recibir cambios y de acceder al espacio compartido.</p><button class="primary" onclick="socialAction133(this,'${user?'remove':'leave'}',{event:'${id}'${user?`,user:'${user}'`:''}})">Confirmar</button>`)}
function modalPublish133(id){const p=social133.posts.find(p=>p.bolo_id===id),g=gigs.find(g=>g.id===id);socialModal133('Compartir con mis amigos',`<h3>${esc(projectById(g.project_id).name)}</h3><p>Si lo activas, el día del bolo tus amigos verán tu nombre, el proyecto y la localidad que escribas aquí. No verán el recinto exacto, horarios ni datos personales.</p><form class="form" onsubmit="publishSocial133(event,'${id}')"><label>Localidad que quieres mostrar<input id="socialCity133" maxlength="120" value="${esc(p?.city||'')}" placeholder="Por ejemplo: Barcelona"></label><label class="export-check"><input id="socialVisible133" type="checkbox" ${p?.visible?'checked':''}> Mostrar este bolo en «Hoy tocan…»</label><button class="primary">Guardar visibilidad</button></form>`)}
async function publishSocial133(event,id){event.preventDefault();await socialAction133(event.target.querySelector('button'),'publish',{bolo:id,city:document.getElementById('socialCity133').value.trim(),visible:document.getElementById('socialVisible133').checked})}
function modalCheer133(id){const p=social133.feed.find(p=>p.id===id);if(!p)return;socialModal133('Enviar ánimo',`<p>Nota privada para <b>${esc(p.name)}</b>.</p><form class="form" onsubmit="event.preventDefault();socialAction133(this.querySelector('button'),'cheer',{post:'${id}',message:document.getElementById('cheerMessage133').value.trim()})"><label>Tu mensaje<textarea id="cheerMessage133" required maxlength="280" rows="3" placeholder="¡Que salga genial esta noche!"></textarea></label><button class="primary">Enviar ánimo</button></form>`)}
function socialMemories133(e){return `<section class="social-card"><h2>Recuerdos compartidos</h2><p class="muted">Solo los participantes aceptados pueden ver estos recuerdos.</p>${social133.memories.filter(m=>m.event_id===e.id).map(m=>{const photo=socialPhotos133.get(m.photo_path);return `<article class="social-memory social-person"><div class="grow"><b>${esc(m.name)}</b><p class="social-note">${esc(m.message)}</p>${photo?.expires>Date.now()?`<img src="${esc(photo.url)}" alt="Recuerdo del bolo" loading="lazy">`:m.photo_path?'<p class="muted">Foto no disponible. Actualiza Amigos para reintentar.</p>':''}<small>${socialDate133(m.created_at)}</small>${m.user_id===session.user.id?`<button class="secondary" onclick="socialAction133(this,'hide_memory',{event:'${e.id}',id:'${m.id}'})">Ocultar recuerdo</button>`:''}</div></article>`}).join('')}<button class="secondary" onclick="modalMemory133('${e.id}')">Añadir recuerdo</button></section>`}
function modalMemory133(id){socialModal133('Añadir recuerdo',`<form class="form" onsubmit="saveMemory133(event,'${id}')"><label>Unas palabras<textarea id="memoryMessage133" maxlength="500" rows="3"></textarea></label><label>Foto opcional · máximo 5 MB<input id="memoryPhoto133" type="file" accept="image/jpeg,image/png,image/webp"></label><label class="export-check"><input id="memoryConsent133" type="checkbox" required> Tengo permiso para compartir este contenido con los participantes del bolo.</label><button class="primary">Guardar recuerdo</button></form>`)}
async function saveMemory133(event,id){event.preventDefault();const button=event.target.querySelector('button'),file=document.getElementById('memoryPhoto133').files[0],msg=document.getElementById('memoryMessage133').value.trim();button.disabled=true;try{let path=event.target.dataset.photoPath||'';if(file&&!path){if(!['image/jpeg','image/png','image/webp'].includes(file.type)||file.size>5242880)throw Error('Elige una foto JPG, PNG o WebP de hasta 5 MB');path=id+'/'+session.user.id+'/'+crypto.randomUUID()+({ 'image/jpeg':'.jpg','image/png':'.png','image/webp':'.webp'}[file.type]);const {error}=await db.storage.from('ritmo-social').upload(path,file,{contentType:file.type,upsert:false});if(error)throw error;event.target.dataset.photoPath=path}await socialRpc133('memory',{event:id,message:msg,photo:path});await loadSocial133(false);closeModal();render()}catch(e){document.getElementById('socialModalError133').innerHTML=`<div class="error">${esc(e.message)}</div>`}finally{button.disabled=false}}
// Actualización discreta mientras la app está visible; sin push ni mensajes externos.
setInterval(()=>{if(!socialWriting133&&session&&!needsAccountSetup()&&!accountBlocked132&&document.visibilityState==='visible'&&!document.getElementById('modal'))loadSocial133(['friends','shared'].includes(view))},60000);
