/* RITMO 1.39: puesta en marcha, avisos y compartir actuaciones. */

function installed139(){return matchMedia('(display-mode: standalone)').matches||navigator.standalone===true}
function installGuide139(){return `<section class="card install-guide139"><div class="eyebrow">PRIMER PASO</div><h2>RITMO en tu pantalla de inicio</h2><p>Ábrelo desde su icono para usarlo como una app.</p><div class="install-platforms139"><div><b>iPhone · Safari</b><span>Pulsa Compartir y después «Añadir a pantalla de inicio».</span></div><div><b>Android · Chrome</b><span>Abre el menú de tres puntos y elige «Instalar aplicación» o «Añadir a pantalla de inicio».</span></div></div></section>`}
function modalInstall139(){socialModal133('Instala RITMO',installGuide139())}
const initialStepsBase139=initialSteps131;
initialSteps131=function(){return [{id:'install',title:'Añadir RITMO a la pantalla de inicio',text:'iPhone: Safari → Compartir → Añadir a pantalla de inicio. Android: Chrome → ⋮ → Instalar aplicación o Añadir a pantalla de inicio.',done:installed139(),action:'modalInstall139()'},...initialStepsBase139()]};
tourSteps131.unshift(['header .brand','Instala RITMO','En iPhone: abre RITMO en Safari, pulsa Compartir y «Añadir a pantalla de inicio». En Android: abre Chrome, pulsa ⋮ y «Instalar aplicación» o «Añadir a pantalla de inicio».']);
const helpBase139=help131;
help131=function(){return helpBase139().replace('<section class="card"><h2>Un paseo por RITMO',installGuide139()+'<section class="card"><h2>Un paseo por RITMO')};

/* El domicilio pertenece a la cuenta. El proyecto predeterminado no se modifica aquí. */
const travelModalBase139=modalTravelSettings;
modalTravelSettings=function(){travelModalBase139();document.getElementById('sdefaultproject')?.closest('label')?.remove();document.getElementById('shome')?.closest('label')?.insertAdjacentHTML('beforebegin','<p class="muted travel-home-note139">Este es tu domicilio personal para calcular las rutas de todos tus bolos, sea cual sea el proyecto.</p>')};
saveTravelSettings=async function(event){event.preventDefault();const err=document.getElementById('settingsError');err.innerHTML='';const payload={home_address:document.getElementById('shome').value.trim(),average_speed_kmh:Number(document.getElementById('sspeed').value||0),departure_margin_minutes:Number(document.getElementById('smargin').value||0),updated_at:new Date().toISOString()};const query=window.userSettings?.user_id?db.from('user_settings').update(payload).eq('user_id',session.user.id):db.from('user_settings').insert({...payload,user_id:session.user.id});const {error}=await query;if(error){err.innerHTML=`<div class="error">${esc(error.message)}</div>`;return}await loadUserSettings();closeModal();render()};
const kmModalBase139=modalKmPrices;
modalKmPrices=function(){kmModalBase139();document.getElementById('kpprice')?.closest('label')?.insertAdjacentHTML('beforebegin','<label class="export-check no-km139"><input id="kpNone139" type="checkbox" onchange="toggleNoKm139(this)"> No aplicar tarifa por km</label>')};
function toggleNoKm139(box){const input=document.getElementById('kpprice');if(!input)return;input.disabled=box.checked;if(box.checked)input.value='0';else input.value=''}

/* El saludo de medianoche corresponde a la noche anterior. */
greeting=function(){const hour=new Date().getHours();return hour>=5&&hour<13?'Buenos días':hour>=13&&hour<20?'Buenas tardes':'Buenas noches'};

/* La foto de perfil usa la carpeta del usuario ya permitida en ritmo-files. */
const profileModalBase139=modalProfile;
modalProfile=function(){profileModalBase139();const field=document.getElementById('profileName');if(!field||document.getElementById('avatarFile139'))return;field.closest('label')?.insertAdjacentHTML('afterend',`<label>Foto o avatar<input id="avatarFile139" type="file" accept="image/jpeg,image/png,image/webp"></label><p class="muted">Opcional · JPG, PNG o WebP de hasta 2 MB.</p>${window.userSettings?.avatar_url?`<img class="profile-avatar139" src="${esc(window.userSettings.avatar_url)}" alt="Tu avatar actual">`:''}`)};
saveProfile=async function(event){event.preventDefault();const button=event.target.querySelector('button.primary'),err=document.getElementById('profileError'),file=document.getElementById('avatarFile139')?.files[0];if(button.disabled)return;button.disabled=true;err.innerHTML='';try{if(file&&(!['image/jpeg','image/png','image/webp'].includes(file.type)||file.size>2*1024*1024))throw Error('Elige una imagen JPG, PNG o WebP de hasta 2 MB.');const avatar=file?await uploadBoloFile(file,'avatar'):window.userSettings?.avatar_url||null;const payload={display_name:document.getElementById('profileName').value.trim(),avatar_url:avatar,updated_at:new Date().toISOString()},query=window.userSettings?.user_id?db.from('user_settings').update(payload).eq('user_id',session.user.id):db.from('user_settings').insert({...payload,user_id:session.user.id});const {error}=await query;if(error)throw error;await loadUserSettings();closeModal();render()}catch(e){err.innerHTML=`<div class="error">${esc(e.message)}</div>`}finally{button.disabled=false}};

/* Los datos opcionales de Hoy tocan se consultan solo entre amigos. */
const socialLoadBase139=loadSocial133;
loadSocial133=async function(redraw=true){await socialLoadBase139(false);if(session&&socialOwner133===session.user.id){const {data,error}=await db.rpc('ritmo_social_feed_v139');if(!error&&data){social133.feed=data.feed||[];social133.posts=data.posts||[]}else if(error)console.warn('No se pudieron actualizar las publicaciones:',error.message)}if(redraw&&!document.getElementById('modal')&&tourIndex131<0)render()};
function cityFromPlace139(value){return String(value||'').split(',').map(x=>x.trim()).filter(Boolean).at(-1)||''}
modalPublish133=function(id){const gig=gigs.find(g=>g.id===id),post=social133.posts.find(p=>p.bolo_id===id);if(!gig)return;const city=cityFromPlace139(gig.location);socialModal133('Compartir en «Hoy tocan…»',`<h3>${esc(projectById(gig.project_id).name)}</h3><p class="muted">Tus amigos verán esta publicación el día del bolo. La localidad se toma de la ficha: <b>${esc(city||'pendiente')}</b>.</p>${!city?'<p class="error">Añade la localidad a la ficha para poder publicarlo.</p>':''}<form class="form" onsubmit="publishSocial133(event,'${id}')"><label>Mensaje opcional<textarea id="socialMessage139" maxlength="280" rows="3" placeholder="Hoy tocamos aquí. ¡Nos vemos!">${esc(post?.message||'')}</textarea></label><label class="export-check"><input id="socialLocation139" type="checkbox" ${post?.share_location?'checked':''}> Mostrar también la ubicación completa</label><label class="export-check"><input id="socialPasses139" type="checkbox" ${post?.share_passes?'checked':''}> Mostrar los horarios de los pases</label><label class="export-check"><input id="socialVisible139" type="checkbox" ${post?.visible?'checked':''} ${city?'':'disabled'}> Mostrar el bolo en «Hoy tocan…»</label><p class="muted">No se comparten caché, cobros, gastos, domicilio ni hora de salida.</p><button class="primary" ${city?'':'disabled'}>Guardar publicación</button></form>`)};
publishSocial133=async function(event,id){event.preventDefault();const button=event.target.querySelector('button.primary');if(button.disabled||socialWriting133)return;button.disabled=true;socialWriting133=true;try{const {error}=await db.rpc('ritmo_social_publish_v139',{p_bolo:id,p_visible:document.getElementById('socialVisible139').checked,p_message:document.getElementById('socialMessage139').value.trim(),p_share_location:document.getElementById('socialLocation139').checked,p_share_passes:document.getElementById('socialPasses139').checked});if(error)throw error;await loadSocial133(false);closeModal();render();socialToast133('Publicación guardada')}catch(e){document.getElementById('socialModalError133').innerHTML=`<div class="error">${esc(e.message)}</div>`}finally{socialWriting133=false;button.disabled=false}};
socialFeed133=function(){return `<p class="social-subtle">Solo aparecen los bolos que tus amigos deciden compartir hoy. El organizador elige si muestra la ubicación y los horarios.</p>${social133.feed.map(post=>`<article class="social-card"><div class="social-person"><span class="social-monogram">${socialInitial133(post.name)}</span><div><b>${esc(post.name)} toca hoy</b><small>${esc(post.city)}</small></div></div><div class="social-feed-project">${esc(post.project)}</div>${post.message?`<p class="social-feed-message139">${esc(post.message)}</p>`:''}${post.location?`<p class="social-feed-location139">⌖ ${esc(post.location)} · <a href="https://www.google.com/maps/search/?api=1&amp;query=${encodeURIComponent(post.location)}" target="_blank" rel="noopener">Ver mapa</a></p>`:''}${(post.passes||[]).length?`<div class="social-feed-passes139">${post.passes.map(p=>`<div class="line"><span>Pase ${Number(p.number)} · ${esc(p.type)}</span><b>${esc(String(p.start||'').slice(0,5))}${p.end?' – '+esc(String(p.end).slice(0,5)):''}</b></div>`).join('')}</div>`:''}<div class="social-actions"><button class="secondary" onclick="socialAction133(this,'cheer',{post:'${post.id}',message:'¡Buen bolo!'})">¡Buen bolo!</button><button class="secondary" onclick="socialAction133(this,'cheer',{post:'${post.id}',message:'¡A disfrutar!'})">¡A disfrutar!</button><button class="primary" onclick="modalCheer133('${post.id}')">Enviar ánimo</button></div></article>`).join('')||`<section class="social-card social-empty">${socialIcon133()}<h3>Hoy aún no hay actuaciones compartidas</h3><p>Tus amigos aparecerán aquí cuando publiquen un bolo.</p></section>`}`};

/* Avisos: entradas directas y actualización de la portada mientras la app está visible. */
function unreadStatus139(item){return item.status!=='pending'&&!unreadReply135(item)&&new Date(item.updated_at)>new Date(item.reply_seen_at||item.created_at)}
const activityBase139=activityFeed;
activityFeed=function(){const out=activityBase139();for(const item of out){const title=String(item[1]).toLocaleLowerCase('es');if(/mensaje.*ánimo/.test(title))item[3]='friends:messages';else if(/solicitud|invitación a proyecto/.test(title))item[3]='friends:pending';else if(item[3]==='friends')item[3]='friends:events'}const changed=myFeedback132.filter(unreadStatus139).length;if(changed)out.push(['✎',`${changed} mensaje${changed===1?'':'s'} en revisión o resuelto${changed===1?'':'s'}`,'Administración ha actualizado el estado.','feedback']);return out};
function openActivity139(target){closeModal();if(target.startsWith('friends:'))goFriends136(target.slice(8));else go(target)}
openNotifications=function(){const feed=activityFeed();markNotificationsSeen();document.body.insertAdjacentHTML('beforeend',`<div class="modal-bg" id="modal"><div class="modal activity-modal"><div class="modal-head"><div><h2>Notificaciones</h2><div class="muted">Actividad reciente en RITMO</div></div><button onclick="closeModal();render()">✕</button></div>${feed.length?`<div class="activity-list">${feed.map(item=>`<button class="activity-item" onclick="openActivity139('${esc(item[3])}')"><span class="activity-icon">${item[0]}</span><div><b>${item[1]}</b><span>${item[2]}</span></div><span aria-hidden="true">›</span></button>`).join('')}</div>`:`<div class="activity-empty">✓<br><br>No hay novedades desde tu última visita.</div>`}</div></div>`)};
const todayBase139=todayCenter;
todayCenter=function(gig,owed){const items=todayBase139(gig,owed),cheers=social133.cheers.filter(c=>c.incoming&&!c.seen).length,states=myFeedback132.filter(unreadStatus139).length;if(cheers)items.unshift(['♡',`${cheers} mensaje${cheers===1?'':'s'} de ánimo`,'Abre las palabras de tus amigos',"goFriends136('messages')"]);if(states)items.unshift(['✎','Administración ha actualizado tu mensaje','Consulta su estado en Sugerencias y errores',"go('feedback')"]);return items};
const feedbackRowsBase139=feedbackRows132;
feedbackRows132=function(){let index=0;return feedbackRowsBase139().replace(/<\/article>/g,()=>{const item=myFeedback132[index++];return item&&unreadStatus139(item)?`<p class="feedback-status139">Estado actualizado: ${esc(feedbackStates132[item.status]||item.status)}</p><button class="secondary" onclick="readStatus139(this,'${item.id}')">Marcar actualización vista</button></article>`:'</article>'})};
async function readStatus139(button,id){button.disabled=true;try{const {error}=await db.rpc('ritmo_feedback_read',{p_id:id});if(error)throw error;await loadMyFeedback132();render()}catch(e){alert(e.message)}finally{button.disabled=false}}
function homeUpcoming139(){const rows=gigs.filter(g=>g.event_date>=localDate()&&g.status!=='cancelado').sort((a,b)=>a.event_date.localeCompare(b.event_date)).slice(0,4);return `<section class="card upcoming-simple139"><div class="card-head"><b>Próximos bolos</b><span class="arrow">›</span></div>${rows.map(g=>{const r=boloReadiness(g),percent=r.total?Math.round(r.done/r.total*100):0;return `<button class="upcoming-row139" onclick="goGig('${g.id}')"><span class="upcoming-date139">${new Date(g.event_date+'T12:00:00').toLocaleDateString('es-ES',{day:'numeric',month:'short'})}</span><span class="upcoming-info139"><b>${esc(projectById(g.project_id).name)}</b><small>${esc(g.location||'Ubicación pendiente')} · ${esc(boloStatusLabel(g.status))}</small><span class="upcoming-progress139"><span style="width:${percent}%"></span></span><small>Ficha ${percent}% completa</small></span><span class="arrow" aria-hidden="true">›</span></button>`}).join('')||'<p class="muted">Todavía no hay fechas próximas.</p>'}</section>`}
const homeBase139=home;
home=function(){let html=homeBase139();if(social133.cheers.some(c=>c.incoming&&!c.seen)||myFeedback132.some(unreadStatus139))html=html.replace('class="card today-center"','class="card today-center attention135"');const index=html.indexOf('<div class="upcoming-mini">');if(index>=0)html=html.slice(0,index)+homeUpcoming139();return html};

let lastRefresh139=0;
function refreshSocialAlerts139(){if(!session||needsAccountSetup()||accountBlocked132||document.visibilityState!=='visible'||document.getElementById('modal')||socialWriting133||Date.now()-lastRefresh139<15000)return;lastRefresh139=Date.now();loadSocial133(true).catch(e=>console.warn('Avisos:',e.message))}
document.addEventListener('visibilitychange',()=>{if(document.visibilityState==='visible')refreshSocialAlerts139()});
window.addEventListener('focus',refreshSocialAlerts139);
setInterval(refreshSocialAlerts139,30000);
