/* RITMO 1.32: administración y navegación coherente. */
let adminDashboard132 = {usage:{},feedback:[],history:[]}, adminTab132='users', adminSearch132='';
let myFeedback132=[], feedbackError132='', feedbackLoading132=false, accountBlocked132=false;
let activityOwner132=null;
const activityTimes132=new Map();
const featureLabels132={home:'Inicio',calendar:'Calendario',bolos:'Bolos',reservations:'Reservas',economy:'Mis cobros',expenses:'Gastos',map:'Mapa',stats:'Estadísticas',projects:'Proyectos',checklist:'Checklist',settings:'Ajustes',help:'Guía y primeros pasos',more:'Más',new_bolo:'Añadir bolo',new_payment:'Registrar cobro',route_pdf:'Hoja de ruta PDF',economy_pdf:'PDF de cobros',tour_completed:'Tutorial completado'};
const feedbackStates132={pending:'Pendiente',review:'En revisión',resolved:'Resuelto'};
const historyLabels132={invitation_created:'Invitación creada',invitation_renewed:'Invitación renovada',account_created:'Cuenta creada / invitación',suspended:'Cuenta suspendida',reactivated:'Cuenta reactivada',role_admin:'Rol cambiado a administrador',role_user:'Rol cambiado a usuario',feedback_pending:'Feedback pendiente',feedback_review:'Feedback en revisión',feedback_resolved:'Feedback resuelto'};
function adminIcon132(kind){if(kind==='settings')return '<span class="nav-glyph"><svg viewBox="0 0 24 24" aria-hidden="true"><path d="m9 4 1-2h4l1 2 2 1 2-.2 2 3-1 2v4l1 2-2 3-2-.2-2 1-1 2h-4l-1-2-2-1-2 .2-2-3 1-2v-4l-1-2 2-3 2 .2z"/><circle cx="12" cy="12" r="3"/></svg></span>';return navGlyph(kind==='admin'?'profile':kind==='help'?'checklist':kind==='feedback'?'expenses':kind)}
function menuItems132(){return [['home','Inicio'],['calendar','Calendario'],['bolos','Bolos'],['reservations','Reservas'],['economy','Mis cobros'],['expenses','Gastos'],['map','Mapa'],['stats','Estadísticas'],['projects','Proyectos'],['checklist','Checklist'],['settings','Ajustes'],['help','Guía y primeros pasos'],['feedback','Sugerencias y errores'],...(currentRole==='admin'?[['admin','Administración']]:[]),['refresh','Actualizar datos']]}
const originalMenuIcons1321={home:'⌂',calendar:'▦',bolos:'♫',reservations:'◷',economy:'€',expenses:'↘',map:'⌖',stats:'▥',projects:'🎼',checklist:'☑',admin:'◉',refresh:'↻',help:'☑',feedback:'✎'};
function originalMenuIcon1321(id){return id==='settings'?adminIcon132('settings').replace('class="nav-glyph"','class="dn-icon dn-settings1321"'):'<span class="dn-icon" aria-hidden="true">'+originalMenuIcons1321[id]+'</span>'}
function menuRows132(drawer=false){return menuItems132().map(([id,label])=>`<button onclick="${drawer?'closeMainMenu();':''}${id==='refresh'?'refreshApp()':`go('${id}')`}">${originalMenuIcon1321(id)}<span class="dn-label">${label}</span><span aria-hidden="true">›</span></button>`).join('')}
more = function(){return `${pageTitle('Más')}<nav class="drawer-nav more-original1321" aria-label="Todas las opciones">${menuRows132()}</nav>`};
openMainMenu=function(){closeMainMenu();const n=window.userSettings?.display_name?.trim()||'Mi cuenta';document.body.insertAdjacentHTML('beforeend',`<div class="drawer-bg" id="mainDrawer" onclick="if(event.target===this)closeMainMenu()"><aside class="drawer"><div class="drawer-head">${logo()}<button class="drawer-close" aria-label="Cerrar menú" onclick="closeMainMenu()">✕</button></div><nav class="drawer-nav" aria-label="Todas las opciones">${menuRows132(true)}</nav><div class="drawer-user">${avatarButton()}<div><b>${esc(n)}</b><small>${esc(session?.user?.email||'Cuenta RITMO')}</small></div></div></aside></div>`)};
settingsPage=function(){const items=[['projects','Gestionar proyectos',"go('projects')"],['travel','Configuración de desplazamientos','modalTravelSettings()'],['passes','Tipos de pase','modalPassTypes()'],['travel','Tarifas por km','modalKmPrices()'],['profile','Perfil','modalProfile()'],['feedback','Sugerencias y errores',"go('feedback')"],...(currentRole==='admin'?[['admin','Administración',"go('admin')"]]:[]),['refresh','Actualizar datos','refreshApp()']];return `${pageTitle('Ajustes')}<section class="card settings-guide132"><div>${adminIcon132('help')}<h2>Guía y primeros pasos</h2></div><p class="muted">Descubre RITMO y configura lo necesario para empezar.</p><div class="admin-actions132"><button class="primary" onclick="startTour131()">Ver tutorial</button><button class="secondary" onclick="go('help')">Primeros pasos</button></div></section><nav class="drawer-nav settings-options132" aria-label="Configuración">${items.map(([icon,label,action])=>`<button onclick="${action}">${adminIcon132(icon)}<span class="dn-label">${label}</span><span class="menu-chevron" aria-hidden="true">›</span></button>`).join('')}</nav><button class="secondary" style="margin-top:18px;width:100%" onclick="logout()">Cerrar sesión</button>`};

function resetAdmin132(){adminDashboard132={usage:{},feedback:[],history:[]};adminTab132='users';adminSearch132='';myFeedback132=[];feedbackError132='';feedbackLoading132=false;accountBlocked132=false;activityTimes132.clear();activityOwner132=session?.user?.id||null}
function blockedScreen132(){closeTour131(false);closeModal();closeMainMenu();root.innerHTML=`<div class="splash">${logo()}<div class="card"><h2>Cuenta suspendida</h2><p>El administrador ha pausado tu acceso a RITMO. Tus datos se conservan.</p><button class="secondary" onclick="logout()">Cerrar sesión</button><button class="primary" onclick="start()">Comprobar acceso</button></div></div>`}
const accountStart132=startAccount;
startAccount=async function(){const {data,error}=await db.auth.getSession();if(error)throw error;session=data.session;if(activityOwner132!==session?.user?.id)resetAdmin132();if(session){const result=await db.rpc('ritmo_account_active');if(result.error){root.innerHTML=`<div class="splash">${logo()}<div class="error">No se pudo comprobar el acceso a tu cuenta.</div><button class="primary" onclick="start()">Reintentar</button></div>`;return}accountBlocked132=result.data!==true;if(accountBlocked132){blockedScreen132();return}}await accountStart132();if(session&&!accountBlocked132)recordActivity132('app')};
const renderAdmin132=render;
render=function(){if(accountBlocked132&&session){blockedScreen132();return}if(view==='feedback'&&session&&!needsAccountSetup())root.innerHTML=shell(feedbackPage132());else renderAdmin132()};
const navigate132=go;
go=function(v){if(accountBlocked132){blockedScreen132();return}navigate132(v);window.scrollTo(0,0);if(featureLabels132[v])recordActivity132(v);if(v==='feedback'){myFeedback132=[];feedbackLoading132=true;feedbackError132='';render();loadMyFeedback132()}};
async function recordActivity132(feature){if(!session||accountBlocked132||needsAccountSetup())return;const owner=session.user.id,key=owner+':'+feature,now=Date.now();if(now-(activityTimes132.get(key)||0)<120000)return;activityTimes132.set(key,now);try{const {error}=await db.rpc('ritmo_record_activity',{p_feature:feature});if(error?.code==='42501'&&session?.user?.id===owner){const access=await db.rpc('ritmo_account_active');if(!access.error&&access.data===false){accountBlocked132=true;blockedScreen132()}}}catch(_error){/* La actividad no impide usar la app. */}}
setInterval(()=>{if(document.visibilityState==='visible')recordActivity132('app')},60000);
document.addEventListener('visibilitychange',()=>{if(document.visibilityState==='visible')recordActivity132('app')});
const tourMove132=tourMove131;
tourMove131=function(direction){if(direction>0&&tourIndex131===tourSteps131.length-1)recordActivity132('tour_completed');tourMove132(direction)};
const modalBolo132=modalBolo,modalCobro132=modalCobro,routePdf132=modalRoutePdf131,economyPdf132=printEconomyReport;
modalBolo=function(id=''){if(!id)recordActivity132('new_bolo');return modalBolo132(id)};
modalCobro=function(...args){recordActivity132('new_payment');return modalCobro132(...args)};
modalRoutePdf131=function(id){recordActivity132('route_pdf');return routePdf132(id)};
printEconomyReport=async function(){recordActivity132('economy_pdf');return economyPdf132()};

loadAdminProfiles=async function(){dataProblems131.delete('usuarios');if(currentRole!=='admin'){adminProfiles=[];return}if(view!=='admin')return;if(adminUsersRequest1312)return adminUsersRequest1312;const owner=session?.user?.id;adminUsersLoading1312=true;adminUsersError1312='';const request=(async()=>{try{const {data,error}=await db.rpc('ritmo_admin_dashboard');if(session?.user?.id!==owner||currentRole!=='admin')return;if(error)throw error;if(!data||!Array.isArray(data.users)||!Array.isArray(data.feedback)||!Array.isArray(data.history))throw Error('El servidor no devolvió un panel válido');adminProfiles=data.users;adminDashboard132=data}catch(e){if(session?.user?.id===owner)adminUsersError1312=e.message||'No se pudo actualizar Administración'}finally{if(session?.user?.id===owner)adminUsersLoading1312=false}})();adminUsersRequest1312=request;try{await request}finally{if(adminUsersRequest1312===request)adminUsersRequest1312=null}};
function adminDate132(date){return date?new Date(date).toLocaleString('es-ES',{dateStyle:'short',timeStyle:'short'}):'Sin registro'}
function adminTabSelect132(tab){adminTab132=tab;render()}
function adminSearchUsers132(input){adminSearch132=input.value;document.getElementById('adminUserRows132').innerHTML=adminUserRows132()}
function adminUserRows132(){const q=adminSearch132.trim().toLocaleLowerCase('es');return adminProfiles.filter(p=>!q||(p.name+' '+p.email).toLocaleLowerCase('es').includes(q)).map(p=>`<article class="admin-person132"><div class="admin-person-top132"><div class="grow"><b>${esc(p.name||'Sin nombre')}</b><small>${esc(p.email||'')}</small></div><span class="status ${p.suspended?'unpaid':p.state==='active'?'paid':'reserve'}">${p.suspended?'Suspendido':p.state==='active'?'Activo':p.state==='pending'?'Alta pendiente':'Invitado'}</span></div><div class="admin-facts132"><span>Alta <b>${adminDate132(p.created_at)}</b></span><span>Último inicio de sesión <b>${adminDate132(p.last_sign_in_at)}</b></span><span>Actividad en la app <b>${adminDate132(p.last_active_at)}</b></span><span>Proyectos / bolos <b>${Number(p.projects_count)||0} / ${Number(p.bolos_count)||0}</b></span><span>Tutorial <b>${p.tour_completed?'Completado':'Sin completar registrado'}</b></span></div><div class="admin-actions132">${p.id!==session.user.id?`<label class="admin-role132">Rol<select aria-label="Rol de ${esc(p.name||p.email)}" onchange="changeUserRole('${p.id}',this.value)" ${p.suspended?'disabled':''}><option value="user" ${p.role!=='admin'?'selected':''}>Usuario</option><option value="admin" ${p.role==='admin'?'selected':''}>Administrador</option></select></label>`:'<span class="muted">Tu cuenta administradora</span>'}${p.role!=='admin'?`<button class="secondary ${p.suspended?'':'danger'}" onclick="modalAccountAccess132('${p.id}')">${p.suspended?'Reactivar cuenta':'Suspender cuenta'}</button>`:''}${p.state!=='active'&&!p.suspended?`<button class="secondary" onclick="renewInvite131('${p.id}')">Renovar invitación</button>`:''}</div></article>`).join('')||'<p class="muted">No hay usuarios que coincidan.</p>'}
function adminUsage132(){const u=adminDashboard132.usage||{};return `<div class="admin-metrics132"><div><b>${Number(u.active7)||0}</b><span>Activos · 7 días</span></div><div><b>${Number(u.active30)||0}</b><span>Activos · 30 días</span></div></div><p class="muted">Actividad registrada desde ${u.since?esc(u.since):'la publicación de esta versión'}. Se cuentan aperturas de secciones y herramientas; no su contenido.</p>${(u.features||[]).map(f=>`<div class="line"><span>${esc(featureLabels132[f.feature]||f.feature)}</span><b>${Number(f.users)||0} usuarios · ${Number(f.visits)||0} usos</b></div>`).join('')||'<p class="muted">Todavía no hay actividad registrada.</p>'}`}
function adminFeedback132(){return `<p class="muted">Últimos 100 mensajes. Cada usuario puede consultar el estado de los suyos.</p>${adminDashboard132.feedback.map(f=>`<article class="feedback-card132"><small>${f.kind==='bug'?'Error':'Sugerencia'} · ${adminDate132(f.created_at)}</small><h3>${esc(f.title)}</h3><p class="feedback-message132">${esc(f.message)}</p><small>${esc(f.name)} · ${esc(f.email)}</small><label>Estado<select aria-label="Estado de ${esc(f.title)}" onchange="setFeedbackState132('${f.id}',this.value)">${Object.entries(feedbackStates132).map(([id,name])=>`<option value="${id}" ${f.status===id?'selected':''}>${name}</option>`).join('')}</select></label></article>`).join('')||'<p class="muted">Todavía no hay sugerencias ni errores.</p>'}`}
function adminHistory132(){return `<p class="muted">Últimas 100 acciones, registradas desde esta versión.</p>${adminDashboard132.history.map(h=>`<article class="admin-history132"><b>${esc(historyLabels132[h.action]||h.action)}</b><small>${adminDate132(h.created_at)}</small><p>${esc(h.target_email||'Cuenta ya no disponible')}</p><small>Por ${esc(h.actor_email||'Sistema / Supabase')}</small></article>`).join('')||'<p class="muted">No hay acciones registradas.</p>'}`}
adminView=function(){if(currentRole!=='admin')return `${pageTitle('Administración')}<p class="muted">Esta cuenta no tiene permisos de administración.</p>`;return `${pageTitle('Administración')}<div class="admin-toolbar132"><button class="primary" onclick="modalInviteUser()">Invitar usuario</button><button class="secondary" onclick="retryAdminUsers1312()">Actualizar panel</button></div>${adminUsersLoading1312?'<p role="status" class="muted">Actualizando panel…</p>':''}${adminUsersError1312?`<div class="error" role="alert">No se pudo actualizar Administración. ${esc(adminUsersError1312)}<button class="secondary" onclick="retryAdminUsers1312()">Reintentar</button></div>`:''}<nav class="admin-tabs132" aria-label="Apartados de administración">${[['users','Usuarios'],['usage','Uso'],['feedback','Feedback'],['history','Historial']].map(([id,title])=>`<button class="${id===adminTab132?'active':''}" aria-pressed="${id===adminTab132}" onclick="adminTabSelect132('${id}')">${title}</button>`).join('')}</nav><section class="card">${adminTab132==='users'?`<label class="bolo-search">Buscar usuario<input type="search" value="${esc(adminSearch132)}" placeholder="Nombre o email" oninput="adminSearchUsers132(this)"></label><div id="adminUserRows132">${adminUserRows132()}</div>`:adminTab132==='usage'?adminUsage132():adminTab132==='feedback'?adminFeedback132():adminHistory132()}</section>`};
function modalAccountAccess132(id){const p=adminProfiles.find(p=>p.id===id);if(!p||p.role==='admin'||id===session.user.id)return;closeModal();document.body.insertAdjacentHTML('beforeend',`<div class="modal-bg" id="modal"><div class="modal"><div class="modal-head"><h2>${p.suspended?'Reactivar':'Suspender'} cuenta</h2><button onclick="closeModal()">✕</button></div><p><b>${esc(p.name||p.email)}</b></p><p>${p.suspended?'Volverá a poder acceder a RITMO con sus datos.':'Se bloqueará el acceso a RITMO y se conservarán sus datos. Puedes reactivarla después.'}</p><div id="accountAccessError132" role="status"></div><button class="primary" onclick="setAccountAccess132('${id}',${!p.suspended},this)">Confirmar ${p.suspended?'reactivación':'suspensión'}</button></div></div>`)}
async function setAccountAccess132(id,suspended,button){button.disabled=true;try{const {error}=await db.rpc('ritmo_set_account_access',{p_user_id:id,p_suspended:suspended});if(error)throw error;await loadAdminProfiles();closeModal();render()}catch(e){document.getElementById('accountAccessError132').innerHTML=`<div class="error">${esc(e.message)}</div>`}finally{button.disabled=false}}
async function setFeedbackState132(id,status){try{const {error}=await db.rpc('ritmo_feedback_status',{p_id:id,p_status:status});if(error)throw error;await loadAdminProfiles();render()}catch(e){alert('No se pudo cambiar el estado: '+e.message);render()}}

function feedbackPage132(){return `${pageTitle('Sugerencias y errores')}<section class="card"><h2>Ayúdanos a mejorar RITMO</h2><p class="muted">Cuéntanos tu idea o qué ha fallado. El mensaje lo verá el administrador.</p><form class="form" onsubmit="sendFeedback132(event)"><label>Tipo<select id="feedbackKind132"><option value="suggestion">Sugerencia</option><option value="bug">Comunicar un error</option></select></label><label>Título<input id="feedbackTitle132" required maxlength="120"></label><label>Mensaje<textarea id="feedbackMessage132" rows="5" required maxlength="2000" placeholder="Qué estabas haciendo y qué ocurrió"></textarea></label><div id="feedbackSendError132" role="status"></div><button class="primary">Enviar mensaje</button></form></section><section class="card"><h2>Mis mensajes</h2><div id="feedbackRows132">${feedbackRows132()}</div></section>`}
function feedbackRows132(){return `${feedbackLoading132?'<p class="muted" role="status">Cargando mensajes…</p>':''}${feedbackError132?`<div class="error">${esc(feedbackError132)}<button class="secondary" onclick="loadMyFeedback132()">Reintentar</button></div>`:''}${myFeedback132.map(f=>`<article class="feedback-card132"><span class="status ${f.status==='resolved'?'paid':'reserve'}">${esc(feedbackStates132[f.status])}</span><h3>${esc(f.title)}</h3><p class="feedback-message132">${esc(f.message)}</p><small>${adminDate132(f.created_at)}</small></article>`).join('')||(!feedbackLoading132&&!feedbackError132?'<p class="muted">Aquí verás tus mensajes y su estado.</p>':'')}`};
async function loadMyFeedback132(){const owner=session?.user?.id;feedbackLoading132=true;feedbackError132='';try{const {data,error}=await db.rpc('ritmo_my_feedback');if(error)throw error;if(!Array.isArray(data))throw Error('No se pudieron leer los mensajes');if(session?.user?.id===owner)myFeedback132=data}catch(e){if(session?.user?.id===owner)feedbackError132=e.message}finally{if(session?.user?.id===owner){feedbackLoading132=false;if(view==='feedback'&&document.getElementById('feedbackRows132'))document.getElementById('feedbackRows132').innerHTML=feedbackRows132()}}}
async function sendFeedback132(e){e.preventDefault();const form=e.target;if(form.dataset.saving)return;const title=document.getElementById('feedbackTitle132').value.trim(),message=document.getElementById('feedbackMessage132').value.trim(),err=document.getElementById('feedbackSendError132');if(!title||!message){err.innerHTML='<div class="error">Completa el título y el mensaje.</div>';return}form.dataset.saving='1';const button=form.querySelector('button.primary');button.disabled=true;try{const {error}=await db.rpc('ritmo_send_feedback',{p_kind:document.getElementById('feedbackKind132').value,p_title:title,p_message:message});if(error)throw error;form.reset();const result=await db.rpc('ritmo_my_feedback');if(!result.error&&Array.isArray(result.data))myFeedback132=result.data;render();document.getElementById('feedbackSendError132').innerHTML='<div class="success">Mensaje enviado. Gracias por ayudarnos a mejorar.</div>'}catch(error){err.innerHTML=`<div class="error">${esc(error.message)}</div>`}finally{delete form.dataset.saving;button.disabled=false}}

const invitationInvoke132=db.functions.invoke.bind(db.functions);
db.functions.invoke=async function(name,options){const result=await invitationInvoke132(name,options);if(name==='invite-user'&&result.data?.ok&&!result.error&&options?.body?.email){try{const logged=await db.rpc('ritmo_log_invitation',{p_email:options.body.email,p_renewed:result.data.resend===true});if(logged.error)console.warn('No se pudo registrar la invitación en el historial')}catch(_e){console.warn('No se pudo registrar la invitación en el historial')}}return result};


function projectRailColor1321(g){const color=projectById(g.project_id).color||'#7b4bb7';return /^#(?:[0-9a-f]{3}|[0-9a-f]{6})$/i.test(color)?color:'#7b4bb7'}
